version: '3.8'
services:
  server:
    container_name: server
    build: ./docker
    ports:
      - 8081:443
    volumes:
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./docker/nginx/src:/usr/share/nginx/html